# Generated by Django 5.1.6 on 2025-02-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptioin',
            new_name='description',
        ),
    ]
